import React, { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, BarChart3, Eye, Maximize2, Pin, PinOff, X } from 'lucide-react'
import { ToolbarButton, ToolbarGroup, ToolbarSegmented } from './shared/LayoutPrimitives'
import { WorkspaceSectionBadge } from './shared/OperationalWorkspacePrimitives'
import { buildProjectVisualShowcase, getProjectVisualPins, type ProjectShowcasePreset, type ProjectVisualCard } from './ProjectsVisualShowcase.model'

const PRESETS = [{ value: 'executive', label: 'Executive' }, { value: 'team', label: 'Team review' }]
const stateTone = (state: ProjectVisualCard['state']) => state === 'KNOWN' ? 'emerald' : state === 'ERROR' ? 'rose' : 'amber'

function VisualCard({ visual, pinned, onTogglePin }: { visual: ProjectVisualCard; pinned: boolean; onTogglePin: (id: string) => void }) {
  return <section aria-label={`${visual.title}. ${visual.question}`} data-project-visual-id={visual.id} className="rounded-xl border border-white/10 bg-white/[0.025] p-4 shadow-sm">
    <div className="flex items-start justify-between gap-3"><div><p className="text-[8px] font-black uppercase tracking-[0.18em] text-slate-600">{visual.question}</p><h3 className="mt-1 text-[12px] font-black text-slate-100">{visual.title}</h3></div><div className="flex items-center gap-2"><WorkspaceSectionBadge tone={stateTone(visual.state) as any}>{visual.state === 'KNOWN' ? 'Measured' : visual.state === 'UNKNOWN' ? 'Unknown' : 'Error'}</WorkspaceSectionBadge><button type="button" onClick={() => onTogglePin(visual.id)} aria-label={pinned ? `Unpin ${visual.title}` : `Pin ${visual.title}`} className="rounded-md p-1.5 text-slate-600 hover:bg-white/5 hover:text-white">{pinned ? <PinOff size={12} /> : <Pin size={12} />}</button></div></div>
    <p className="mt-4 text-2xl font-black tracking-tight text-white">{visual.headline}</p><p className="mt-1 text-[10px] leading-4 text-slate-500">{visual.note}</p>
    <div className="mt-4 h-2 overflow-hidden rounded-full bg-white/5" aria-hidden="true"><div className={`h-full rounded-full ${visual.state === 'KNOWN' ? 'bg-blue-500/70' : visual.state === 'ERROR' ? 'bg-rose-500/60' : 'bg-amber-500/45'}`} style={{ width: visual.state === 'KNOWN' ? '72%' : '28%' }} /></div>
    <div className="mt-4 rounded-lg border border-white/5 bg-black/20 p-3" data-project-visual-fallback="true"><table className="w-full text-left text-[9px]"><caption className="sr-only">{visual.title} non-chart fallback</caption><tbody>{visual.fallback.map((row) => <tr key={`${visual.id}-${row.label}`} className="border-b border-white/[0.04] last:border-0"><th className="py-1.5 pr-3 font-black text-slate-600">{row.label}</th><td className="py-1.5 text-right font-semibold text-slate-300">{row.value}</td></tr>)}</tbody></table></div>
    <div className="mt-3 flex items-center justify-between gap-3 text-[8px] text-slate-700" data-project-visual-source="true"><span className="truncate" title={visual.source}>Source · {visual.source}</span><span className="shrink-0">{visual.timeRange}</span></div>
  </section>
}

export function ProjectVisualShowcase({ project, report, snapshot, preset, onPresetChange, onClose, onProjectChange }: any) {
  const model = useMemo(() => buildProjectVisualShowcase({ project, report, snapshot, preset }), [project, report, snapshot, preset])
  const [slide, setSlide] = useState(0)
  const pins = getProjectVisualPins(project)
  const setPins = (nextPins: string[]) => {
    const metadata = project?.metadata_json && typeof project.metadata_json === 'object' ? project.metadata_json : {}
    const reporting = metadata?.project_reporting_v1 && typeof metadata.project_reporting_v1 === 'object' ? metadata.project_reporting_v1 : {}
    onProjectChange?.({ ...project, metadata_json: { ...metadata, project_reporting_v1: { ...reporting, pinned_visual_ids: nextPins.slice(0, 12) } } }, 'Project visual pins updated', `${nextPins.length} visual pin${nextPins.length === 1 ? '' : 's'}`)
  }
  const togglePin = (id: string) => setPins(pins.includes(id) ? pins.filter((item) => item !== id) : [...pins, id])
  const slides = [
    { title: 'Outcome & progress', body: <div className="grid gap-3 lg:grid-cols-2">{model.visuals.filter((item) => model.visualIds.includes(item.id) && ['delivery-progress','adoption-realization','value-realization'].includes(item.id)).map((item) => <VisualCard key={item.id} visual={item} pinned={pins.includes(item.id)} onTogglePin={togglePin} />)}</div> },
    { title: 'Schedule & capacity', body: <div className="grid gap-3 lg:grid-cols-2">{model.visuals.filter((item) => model.visualIds.includes(item.id) && ['milestone-confidence','schedule-health','capacity-health','dependency-map'].includes(item.id)).map((item) => <VisualCard key={item.id} visual={item} pinned={pins.includes(item.id)} onTogglePin={togglePin} />)}</div> },
    { title: 'Risk, evidence & next actions', body: <div className="grid gap-3 lg:grid-cols-2">{model.visuals.filter((item) => model.visualIds.includes(item.id) && ['risk-pressure','collaboration-evidence','flow-health'].includes(item.id)).map((item) => <VisualCard key={item.id} visual={item} pinned={pins.includes(item.id)} onTogglePin={togglePin} />)}<section className="rounded-xl border border-white/10 bg-white/[0.025] p-4"><p className="text-[8px] font-black uppercase tracking-widest text-slate-600">Next actions</p><div className="mt-3 space-y-2">{model.nextActions.length ? model.nextActions.slice(0, 8).map((item) => <p key={item.id} className="rounded-lg border border-white/5 bg-black/20 px-3 py-2 text-[10px] font-semibold text-slate-300">{item.name}</p>) : <p className="text-[10px] text-slate-600">No next actions captured.</p>}</div></section></div> },
  ]
  const current = Math.min(slide, slides.length - 1)
  return <section className="fixed inset-3 z-[120] flex flex-col overflow-hidden rounded-2xl border border-white/10 bg-[#090d16] shadow-2xl sm:inset-5" data-project-showcase={model.preset} data-project-showcase-snapshot={model.frozen ? 'true' : 'false'} aria-label={`${model.name} project showcase`}>
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-white/10 bg-black/25 px-5 py-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><WorkspaceSectionBadge tone="blue">Project Showcase</WorkspaceSectionBadge><WorkspaceSectionBadge tone={model.executionHealth === 'red' ? 'rose' : model.executionHealth === 'amber' ? 'amber' : 'emerald'}>{model.executionHealth} execution</WorkspaceSectionBadge><WorkspaceSectionBadge>{model.outcomeState} outcome</WorkspaceSectionBadge>{model.frozen ? <WorkspaceSectionBadge tone="amber">Frozen · {model.capturedAt || 'timestamp unknown'}</WorkspaceSectionBadge> : <WorkspaceSectionBadge tone="emerald">Live truth</WorkspaceSectionBadge>}</div><h2 className="mt-2 truncate text-xl font-black text-white">{model.name}</h2><p className="mt-1 max-w-4xl text-[11px] leading-5 text-slate-500">{model.objective}</p></div><ToolbarGroup><ToolbarSegmented options={PRESETS} value={model.preset} onChange={(value) => { setSlide(0); onPresetChange?.(value as ProjectShowcasePreset) }} /><ToolbarButton variant="quiet" title="Read-only full-screen presentation"><Maximize2 size={12} /> Read only</ToolbarButton><ToolbarButton variant="quiet" onClick={onClose}><X size={13} /> Close</ToolbarButton></ToolbarGroup></header>
    {model.blockers.length ? <div className="border-b border-rose-500/15 bg-rose-500/[0.05] px-5 py-2 text-[10px] font-semibold text-rose-300">At-risk truth preserved · {model.blockers.map((item) => item.name).slice(0, 3).join(' · ')}</div> : null}
    <main className="min-h-0 flex-1 overflow-y-auto p-5 custom-scrollbar"><div className="mb-4 flex items-center justify-between"><div><p className="text-[8px] font-black uppercase tracking-[0.2em] text-slate-700">Slide {current + 1} / {slides.length}</p><h3 className="mt-1 text-sm font-black text-slate-200">{slides[current].title}</h3></div><div className="flex items-center gap-1"><ToolbarButton variant="quiet" disabled={current === 0} onClick={() => setSlide((value) => Math.max(0, value - 1))}><ArrowLeft size={12} /> Previous</ToolbarButton><ToolbarButton variant="quiet" disabled={current === slides.length - 1} onClick={() => setSlide((value) => Math.min(slides.length - 1, value + 1))}>Next <ArrowRight size={12} /></ToolbarButton></div></div>{slides[current].body}
      <section className="mt-4 rounded-xl border border-white/10 bg-white/[0.02] p-4" aria-label="Visual library"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black uppercase tracking-widest text-slate-700">Visual library</p><p className="mt-1 text-[10px] text-slate-500">Question-driven, provenance-backed visuals. Pinning changes only existing Project reporting metadata.</p></div><BarChart3 size={16} className="text-blue-400" /></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{model.visuals.map((item) => <button key={item.id} type="button" onClick={() => togglePin(item.id)} className="flex items-center justify-between rounded-lg border border-white/5 bg-black/20 px-3 py-2 text-left"><span><b className="block text-[9px] text-slate-300">{item.title}</b><small className="mt-0.5 block text-[8px] text-slate-700">{item.state === 'KNOWN' ? item.headline : item.note}</small></span>{pins.includes(item.id) ? <Pin size={11} className="text-blue-300" /> : <Eye size={11} className="text-slate-700" />}</button>)}</div></section>
    </main>
  </section>
}
