"""sync_projects_schema_v2

Revision ID: 020a1b0da120
Revises: 0acb3f5dc538
Create Date: 2026-04-28 07:49:30.093843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '020a1b0da120'
down_revision: Union[str, Sequence[str], None] = '0acb3f5dc538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env_history',
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_env_history'))
    )
    with op.batch_alter_table('env_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_env_history_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_env_history_id'), ['id'], unique=False)

    op.create_table('project_tasks',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('assigned_objects', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['project_tasks.id'], name=op.f('fk_project_tasks_parent_task_id_project_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_tasks'))
    )
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tasks_name'), ['name'], unique=False)

    op.create_table('project_comments',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_comments_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], name=op.f('fk_project_comments_task_id_project_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_comments'))
    )
    with op.batch_alter_table('project_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_comments_id'), ['id'], unique=False)

    op.create_table('project_qa',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('asked_by', sa.String(), nullable=True),
    sa.Column('answered_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_qa_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], name=op.f('fk_project_qa_task_id_project_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_qa'))
    )
    with op.batch_alter_table('project_qa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_qa_id'), ['id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('jira_links', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('target_systems', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('target_assets', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('target_services', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('beneficiaries', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('problem_statement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('objective', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('key_functions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('expected_outcomes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('parent_project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('roi_defense_line', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('man_hours_saved', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stoploss_minutes_saved', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wafers_gained', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('appendix_json', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_projects_parent_project_id_projects'), 'projects', ['parent_project_id'], ['id'])
        batch_op.drop_column('linked_device_ids')
        batch_op.drop_column('kpis_json')
        batch_op.drop_column('risk_assessment')
        batch_op.drop_column('linked_service_ids')
        batch_op.drop_column('tasks_json')
        batch_op.drop_column('milestones_json')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestones_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tasks_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('linked_service_ids', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('risk_assessment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('kpis_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('linked_device_ids', sqlite.JSON(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_projects_parent_project_id_projects'), type_='foreignkey')
        batch_op.drop_column('appendix_json')
        batch_op.drop_column('wafers_gained')
        batch_op.drop_column('stoploss_minutes_saved')
        batch_op.drop_column('man_hours_saved')
        batch_op.drop_column('roi_defense_line')
        batch_op.drop_column('parent_project_id')
        batch_op.drop_column('expected_outcomes')
        batch_op.drop_column('key_functions')
        batch_op.drop_column('objective')
        batch_op.drop_column('problem_statement')
        batch_op.drop_column('beneficiaries')
        batch_op.drop_column('target_services')
        batch_op.drop_column('target_assets')
        batch_op.drop_column('target_systems')
        batch_op.drop_column('jira_links')
        batch_op.drop_column('type')

    with op.batch_alter_table('project_qa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_qa_id'))

    op.drop_table('project_qa')
    with op.batch_alter_table('project_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_comments_id'))

    op.drop_table('project_comments')
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tasks_name'))
        batch_op.drop_index(batch_op.f('ix_project_tasks_id'))

    op.drop_table('project_tasks')
    with op.batch_alter_table('env_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_env_history_id'))
        batch_op.drop_index(batch_op.f('ix_env_history_field'))

    op.drop_table('env_history')
    # ### end Alembic commands ###
