"""add_owner_team_status_env_to_external_entities

Revision ID: 057a20e6c065
Revises: 8089cfa51347
Create Date: 2026-04-14 07:14:22.184654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057a20e6c065'
down_revision: Union[str, Sequence[str], None] = '8089cfa51347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_team', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('environment', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_entities', schema=None) as batch_op:
        batch_op.drop_column('environment')
        batch_op.drop_column('status')
        batch_op.drop_column('owner_team')

    # ### end Alembic commands ###
