"""add_far_and_bkm_modules

Revision ID: 066668880dda
Revises: 09b3ab8d3866
Create Date: 2026-04-01 13:50:23.680606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066668880dda'
down_revision: Union[str, Sequence[str], None] = '09b3ab8d3866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('far_failure_causes',
    sa.Column('cause_text', sa.Text(), nullable=True),
    sa.Column('occurrence_level', sa.Integer(), nullable=True),
    sa.Column('responsible_team', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_far_failure_causes'))
    )
    with op.batch_alter_table('far_failure_causes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_far_failure_causes_id'), ['id'], unique=False)

    op.create_table('far_failure_modes',
    sa.Column('system_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('occurrence', sa.Integer(), nullable=True),
    sa.Column('detection', sa.Integer(), nullable=True),
    sa.Column('rpn', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('has_incident_history', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_far_failure_modes'))
    )
    with op.batch_alter_table('far_failure_modes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_far_failure_modes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_far_failure_modes_system_name'), ['system_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_far_failure_modes_title'), ['title'], unique=False)

    op.create_table('far_mode_assets',
    sa.Column('mode_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_far_mode_assets_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mode_id'], ['far_failure_modes.id'], name=op.f('fk_far_mode_assets_mode_id_far_failure_modes'), ondelete='CASCADE')
    )
    op.create_table('far_mode_causes',
    sa.Column('mode_id', sa.Integer(), nullable=True),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['far_failure_causes.id'], name=op.f('fk_far_mode_causes_cause_id_far_failure_causes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mode_id'], ['far_failure_modes.id'], name=op.f('fk_far_mode_causes_mode_id_far_failure_modes'), ondelete='CASCADE')
    )
    op.create_table('far_prevention',
    sa.Column('failure_mode_id', sa.Integer(), nullable=True),
    sa.Column('prevention_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('responsible_team', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['far_failure_modes.id'], name=op.f('fk_far_prevention_failure_mode_id_far_failure_modes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_far_prevention'))
    )
    with op.batch_alter_table('far_prevention', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_far_prevention_id'), ['id'], unique=False)

    op.create_table('far_resolutions',
    sa.Column('knowledge_id', sa.Integer(), nullable=True),
    sa.Column('preventive_follow_up', sa.Text(), nullable=True),
    sa.Column('responsible_team', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_entries.id'], name=op.f('fk_far_resolutions_knowledge_id_knowledge_entries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_far_resolutions'))
    )
    with op.batch_alter_table('far_resolutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_far_resolutions_id'), ['id'], unique=False)

    op.create_table('far_cause_resolutions',
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('resolution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['far_failure_causes.id'], name=op.f('fk_far_cause_resolutions_cause_id_far_failure_causes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolution_id'], ['far_resolutions.id'], name=op.f('fk_far_cause_resolutions_resolution_id_far_resolutions'), ondelete='CASCADE')
    )
    op.create_table('far_mitigations',
    sa.Column('mitigation_type', sa.String(), nullable=True),
    sa.Column('mitigation_steps', sa.Text(), nullable=True),
    sa.Column('responsible_team', sa.String(), nullable=True),
    sa.Column('monitoring_item_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['monitoring_item_id'], ['monitoring_items.id'], name=op.f('fk_far_mitigations_monitoring_item_id_monitoring_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_far_mitigations'))
    )
    with op.batch_alter_table('far_mitigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_far_mitigations_id'), ['id'], unique=False)

    op.create_table('far_mode_mitigations',
    sa.Column('mode_id', sa.Integer(), nullable=True),
    sa.Column('mitigation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mitigation_id'], ['far_mitigations.id'], name=op.f('fk_far_mode_mitigations_mitigation_id_far_mitigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mode_id'], ['far_failure_modes.id'], name=op.f('fk_far_mode_mitigations_mode_id_far_failure_modes'), ondelete='CASCADE')
    )
    with op.batch_alter_table('knowledge_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_entries', schema=None) as batch_op:
        batch_op.drop_column('content_json')

    op.drop_table('far_mode_mitigations')
    with op.batch_alter_table('far_mitigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_far_mitigations_id'))

    op.drop_table('far_mitigations')
    op.drop_table('far_cause_resolutions')
    with op.batch_alter_table('far_resolutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_far_resolutions_id'))

    op.drop_table('far_resolutions')
    with op.batch_alter_table('far_prevention', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_far_prevention_id'))

    op.drop_table('far_prevention')
    op.drop_table('far_mode_causes')
    op.drop_table('far_mode_assets')
    with op.batch_alter_table('far_failure_modes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_far_failure_modes_title'))
        batch_op.drop_index(batch_op.f('ix_far_failure_modes_system_name'))
        batch_op.drop_index(batch_op.f('ix_far_failure_modes_id'))

    op.drop_table('far_failure_modes')
    with op.batch_alter_table('far_failure_causes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_far_failure_causes_id'))

    op.drop_table('far_failure_causes')
    # ### end Alembic commands ###
