"""add_troubleshooting_fields_to_investigation

Revision ID: 09b3ab8d3866
Revises: c4ebee015e2d
Create Date: 2026-04-01 12:30:43.583911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b3ab8d3866'
down_revision: Union[str, Sequence[str], None] = 'c4ebee015e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigation_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poc', sa.String(), nullable=True))

    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('impact', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mitigation_items', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('prevention_method', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('monitoring_items', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_column('monitoring_items')
        batch_op.drop_column('prevention_method')
        batch_op.drop_column('mitigation_items')
        batch_op.drop_column('impact')
        batch_op.drop_column('category')

    with op.batch_alter_table('investigation_progress', schema=None) as batch_op:
        batch_op.drop_column('poc')

    # ### end Alembic commands ###
