"""add_global_settings_and_user_preferences

Revision ID: 0acb3f5dc538
Revises: d1e55c4db1ab
Create Date: 2026-04-27 09:22:41.874683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acb3f5dc538'
down_revision: Union[str, Sequence[str], None] = 'd1e55c4db1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_settings'))
    )
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_settings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_settings_key'), ['key'], unique=True)

    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_key'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_settings_key'))
        batch_op.drop_index(batch_op.f('ix_global_settings_id'))
        batch_op.drop_index(batch_op.f('ix_global_settings_category'))

    op.drop_table('global_settings')
    # ### end Alembic commands ###
