"""sync rca and investigation schema v4

Revision ID: 0d7c82f2d2a9
Revises: f25553f893a1
Create Date: 2026-04-20 15:37:44.519417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7c82f2d2a9'
down_revision: Union[str, Sequence[str], None] = 'f25553f893a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rca_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mitigation_logs_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rca_records', schema=None) as batch_op:
        batch_op.drop_column('mitigation_logs_json')

    # ### end Alembic commands ###
