"""add aisle and row to racks

Revision ID: 1038b4c0ad51
Revises: 8847b4d2f9b7
Create Date: 2026-05-20 15:11:43.415927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1038b4c0ad51'
down_revision: Union[str, Sequence[str], None] = '8847b4d2f9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aisle', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('row', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_column('row')
        batch_op.drop_column('aisle')

    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
