"""add failure_type to far

Revision ID: 1050956bd84e
Revises: 63ee971aa974
Create Date: 2026-04-22 07:45:33.686993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1050956bd84e'
down_revision: Union[str, Sequence[str], None] = '63ee971aa974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('far_failure_modes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failure_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('far_failure_modes', schema=None) as batch_op:
        batch_op.drop_column('failure_type')

    # ### end Alembic commands ###
