"""sync_rca_and_investigation_v3

Revision ID: 17a97a934a75
Revises: f7a7a7f2a4d0
Create Date: 2026-04-15 14:43:25.011955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a97a934a75'
down_revision: Union[str, Sequence[str], None] = 'f7a7a7f2a4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rca_failure_mode_links',
    sa.Column('rca_id', sa.Integer(), nullable=True),
    sa.Column('failure_mode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['far_failure_modes.id'], name=op.f('fk_rca_failure_mode_links_failure_mode_id_far_failure_modes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rca_id'], ['rca_records.id'], name=op.f('fk_rca_failure_mode_links_rca_id_rca_records'), ondelete='CASCADE')
    )
    with op.batch_alter_table('external_entity_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_entity_secrets_id'), ['id'], unique=False)

    with op.batch_alter_table('rca_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem_statement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('occurrence_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('jira_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('impacted_service_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('fab_impact_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('identification_steps_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rca_steps_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('potential_causes_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('rca_timeline_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('owner_team', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rca_timeline_events', schema=None) as batch_op:
        batch_op.drop_column('owner_team')
        batch_op.drop_column('owner')

    with op.batch_alter_table('rca_records', schema=None) as batch_op:
        batch_op.drop_column('potential_causes_json')
        batch_op.drop_column('rca_steps_json')
        batch_op.drop_column('identification_steps_json')
        batch_op.drop_column('fab_impact_json')
        batch_op.drop_column('impacted_service_ids')
        batch_op.drop_column('jira_link')
        batch_op.drop_column('owner')
        batch_op.drop_column('acknowledged_at')
        batch_op.drop_column('occurrence_at')
        batch_op.drop_column('priority')
        batch_op.drop_column('problem_statement')

    with op.batch_alter_table('external_entity_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_entity_secrets_id'))

    op.drop_table('rca_failure_mode_links')
    # ### end Alembic commands ###
