"""sync_projects_roi_and_owners

Revision ID: 1f9dc5823025
Revises: 60cee6033e86
Create Date: 2026-05-26 10:00:10.251871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9dc5823025'
down_revision: Union[str, Sequence[str], None] = '60cee6033e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owners', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('roi_defense_line_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('man_hours_saved_math', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('man_hours_saved_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stoploss_minutes_saved_math', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stoploss_minutes_saved_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wafers_gained_math', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wafers_gained_desc', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('wafers_gained_desc')
        batch_op.drop_column('wafers_gained_math')
        batch_op.drop_column('stoploss_minutes_saved_desc')
        batch_op.drop_column('stoploss_minutes_saved_math')
        batch_op.drop_column('man_hours_saved_desc')
        batch_op.drop_column('man_hours_saved_math')
        batch_op.drop_column('roi_defense_line_desc')
        batch_op.drop_column('owners')

    # ### end Alembic commands ###
