"""add external intelligence tables

Revision ID: 256902a5e7d9
Revises: 77eb5cdb6c8a
Create Date: 2026-03-31 12:21:06.364297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256902a5e7d9'
down_revision: Union[str, Sequence[str], None] = '77eb5cdb6c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_entities',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('owner_organization', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_entities'))
    )
    with op.batch_alter_table('external_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_entities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_entities_name'), ['name'], unique=False)

    op.create_table('external_links',
    sa.Column('external_entity_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_external_links_device_id_devices')),
    sa.ForeignKeyConstraint(['external_entity_id'], ['external_entities.id'], name=op.f('fk_external_links_external_entity_id_external_entities')),
    sa.ForeignKeyConstraint(['service_id'], ['logical_services.id'], name=op.f('fk_external_links_service_id_logical_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_links'))
    )
    with op.batch_alter_table('external_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_links_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_links_id'))

    op.drop_table('external_links')
    with op.batch_alter_table('external_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_entities_name'))
        batch_op.drop_index(batch_op.f('ix_external_entities_id'))

    op.drop_table('external_entities')
    # ### end Alembic commands ###
