"""add_monitoring_reliability_fields

Revision ID: 26f7a74f2a4d
Revises: 5855d04ab558
Create Date: 2026-04-09 10:12:19.502284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f7a74f2a4d'
down_revision: Union[str, Sequence[str], None] = '5855d04ab558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alert_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notification_throttle', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recovery_docs', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.drop_column('recovery_docs')
        batch_op.drop_column('is_active')
        batch_op.drop_column('severity')
        batch_op.drop_column('notification_throttle')
        batch_op.drop_column('alert_duration')
        batch_op.drop_column('check_interval')

    # ### end Alembic commands ###
