"""add_risk_to_firewall

Revision ID: 370e69388728
Revises: 5383bf931a78
Create Date: 2026-03-31 09:44:32.281447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370e69388728'
down_revision: Union[str, Sequence[str], None] = '5383bf931a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firewall_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk', sa.Text(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firewall_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('risk')

    # ### end Alembic commands ###
