"""add projects table

Revision ID: 3860f2d3a61b
Revises: b50f3c68f0a2
Create Date: 2026-04-02 12:03:01.692722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3860f2d3a61b'
down_revision: Union[str, Sequence[str], None] = 'b50f3c68f0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_coverage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_coverage_id'))

    op.drop_table('contract_coverage')
    with op.batch_alter_table('data_flows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_flows', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('contract_coverage',
    sa.Column('contract_id', sa.INTEGER(), nullable=True),
    sa.Column('device_id', sa.INTEGER(), nullable=True),
    sa.Column('support_tier', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['vendor_contracts.id'], name=op.f('fk_contract_coverage_contract_id_vendor_contracts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_contract_coverage_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_coverage'))
    )
    with op.batch_alter_table('contract_coverage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_coverage_id'), ['id'], unique=False)

    # ### end Alembic commands ###
