"""add_actual_dates_to_project_tasks

Revision ID: 3e604a042903
Revises: 99c650300ac3
Create Date: 2026-05-26 10:20:08.862925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e604a042903'
down_revision: Union[str, Sequence[str], None] = '99c650300ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_column('actual_end_date')
        batch_op.drop_column('actual_start_date')

    # ### end Alembic commands ###
