"""add monitoring owners table

Revision ID: 45d2a3a171dc
Revises: e72b9b8626d3
Create Date: 2026-04-09 15:25:30.436624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d2a3a171dc'
down_revision: Union[str, Sequence[str], None] = 'e72b9b8626d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_owners',
    sa.Column('monitoring_item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['monitoring_item_id'], ['monitoring_items.id'], name=op.f('fk_monitoring_owners_monitoring_item_id_monitoring_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitoring_owners'))
    )
    with op.batch_alter_table('monitoring_owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_owners_id'), ['id'], unique=False)

    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.drop_column('owner')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('owner', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('monitoring_owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_owners_id'))

    op.drop_table('monitoring_owners')
    # ### end Alembic commands ###
