"""add dependencies to project tasks v2

Revision ID: 485b2b4beada
Revises: 020a1b0da120
Create Date: 2026-04-28 10:20:02.390639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485b2b4beada'
down_revision: Union[str, Sequence[str], None] = '020a1b0da120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dependencies_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('estimate_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_column('estimate_hours')
        batch_op.drop_column('dependencies_json')

    # ### end Alembic commands ###
