"""add_teams_to_operators

Revision ID: 4bf78a8a9f23
Revises: 9c4d6e7f8a10
Create Date: 2026-06-09 13:18:21.025404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf78a8a9f23'
down_revision: Union[str, Sequence[str], None] = '9c4d6e7f8a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teams', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.drop_column('teams')

    # ### end Alembic commands ###
