"""sync far mitigation and prevention columns

Revision ID: 4fb7471f58a3
Revises: 1050956bd84e
Create Date: 2026-04-22 12:52:18.000903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb7471f58a3'
down_revision: Union[str, Sequence[str], None] = '1050956bd84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('far_mitigations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cause_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_far_mitigations_cause_id_far_failure_causes'), 'far_failure_causes', ['cause_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('far_prevention', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cause_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_far_prevention_cause_id_far_failure_causes'), 'far_failure_causes', ['cause_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('far_prevention', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_far_prevention_cause_id_far_failure_causes'), type_='foreignkey')
        batch_op.drop_column('cause_id')

    with op.batch_alter_table('far_mitigations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_far_mitigations_cause_id_far_failure_causes'), type_='foreignkey')
        batch_op.drop_column('cause_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
