"""add_ip_to_connections

Revision ID: 5383bf931a78
Revises: 8596642f109d
Create Date: 2026-03-31 09:31:51.828336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5383bf931a78'
down_revision: Union[str, Sequence[str], None] = '8596642f109d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_ip', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target_ip', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.drop_column('target_ip')
        batch_op.drop_column('source_ip')

    # ### end Alembic commands ###
