"""add_images_to_rca_timeline

Revision ID: 63ee971aa974
Revises: 0d7c82f2d2a9
Create Date: 2026-04-21 07:09:26.443455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ee971aa974'
down_revision: Union[str, Sequence[str], None] = '0d7c82f2d2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rca_timeline_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rca_timeline_events', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
