"""add monitored services to monitoring item

Revision ID: 77eb5cdb6c8a
Revises: e30fab364540
Create Date: 2026-03-31 11:24:58.303390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77eb5cdb6c8a'
down_revision: Union[str, Sequence[str], None] = 'e30fab364540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitored_services', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.drop_column('monitored_services')

    # ### end Alembic commands ###
