"""revamp_external_entities_for_metadata_and_poc

Revision ID: 8089cfa51347
Revises: 5ff12d0da4c3
Create Date: 2026-04-13 16:34:38.679608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8089cfa51347'
down_revision: Union[str, Sequence[str], None] = '5ff12d0da4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poc_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.drop_column('contact_info')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('hostname')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostname', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('contact_info', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('poc_json')

    # ### end Alembic commands ###
