"""Initial schema

Revision ID: 8596642f109d
Revises: 
Create Date: 2026-03-31 08:31:18.673232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8596642f109d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target_table', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('data_flows',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('nodes_json', sa.JSON(), nullable=True),
    sa.Column('edges_json', sa.JSON(), nullable=True),
    sa.Column('viewport_json', sa.JSON(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_flows'))
    )
    with op.batch_alter_table('data_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_flows_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_flows_name'), ['name'], unique=False)

    op.create_table('devices',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('size_u', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('asset_tag', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('management_ip', sa.String(), nullable=True),
    sa.Column('primary_ip', sa.String(), nullable=True),
    sa.Column('management_url', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('business_unit', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('purchase_order', sa.String(), nullable=True),
    sa.Column('cost_center', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('install_date', sa.DateTime(), nullable=True),
    sa.Column('warranty_end', sa.DateTime(), nullable=True),
    sa.Column('eol_date', sa.DateTime(), nullable=True),
    sa.Column('power_supply_count', sa.Integer(), nullable=True),
    sa.Column('power_max_w', sa.Float(), nullable=True),
    sa.Column('power_typical_w', sa.Float(), nullable=True),
    sa.Column('btu_hr', sa.Float(), nullable=True),
    sa.Column('depth', sa.String(), nullable=True),
    sa.Column('tool_group', sa.String(), nullable=True),
    sa.Column('fab_area', sa.String(), nullable=True),
    sa.Column('recipe_critical', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_reservation', sa.Boolean(), nullable=True),
    sa.Column('reservation_info', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_asset_tag'), ['asset_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_system'), ['system'], unique=False)

    op.create_table('incident_logs',
    sa.Column('systems', sa.JSON(), nullable=True),
    sa.Column('impacted_device_ids', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('reporter', sa.String(), nullable=True),
    sa.Column('initial_symptoms', sa.Text(), nullable=True),
    sa.Column('impacts_json', sa.JSON(), nullable=True),
    sa.Column('impact_analysis', sa.Text(), nullable=True),
    sa.Column('trigger_event', sa.Text(), nullable=True),
    sa.Column('log_evidence', sa.Text(), nullable=True),
    sa.Column('mitigation_steps', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('resolution_steps', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('prevention_strategy', sa.Text(), nullable=True),
    sa.Column('timeline_json', sa.JSON(), nullable=True),
    sa.Column('todos_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_logs'))
    )
    with op.batch_alter_table('incident_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_logs_title'), ['title'], unique=False)

    op.create_table('settings_options',
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata_keys', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings_options'))
    )
    with op.batch_alter_table('settings_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_options_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_options_id'), ['id'], unique=False)

    op.create_table('sites',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('facility_manager', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('cooling_capacity_kw', sa.Float(), nullable=True),
    sa.Column('power_capacity_kw', sa.Float(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites'))
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_name'), ['name'], unique=True)

    op.create_table('subnets',
    sa.Column('network_cidr', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('dns_servers', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subnets'))
    )
    with op.batch_alter_table('subnets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subnets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subnets_network_cidr'), ['network_cidr'], unique=True)

    op.create_table('device_relationships',
    sa.Column('source_device_id', sa.Integer(), nullable=True),
    sa.Column('target_device_id', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('source_role', sa.String(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], name=op.f('fk_device_relationships_source_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], name=op.f('fk_device_relationships_target_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_relationships'))
    )
    with op.batch_alter_table('device_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_relationships_id'), ['id'], unique=False)

    op.create_table('device_software',
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('install_date', sa.DateTime(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_software_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_software'))
    )
    with op.batch_alter_table('device_software', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_software_id'), ['id'], unique=False)

    op.create_table('firewall_rules',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_device_id', sa.Integer(), nullable=True),
    sa.Column('source_subnet_id', sa.Integer(), nullable=True),
    sa.Column('source_custom_ip', sa.String(), nullable=True),
    sa.Column('dest_type', sa.String(), nullable=True),
    sa.Column('dest_device_id', sa.Integer(), nullable=True),
    sa.Column('dest_subnet_id', sa.Integer(), nullable=True),
    sa.Column('dest_custom_ip', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('port_range', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dest_device_id'], ['devices.id'], name=op.f('fk_firewall_rules_dest_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dest_subnet_id'], ['subnets.id'], name=op.f('fk_firewall_rules_dest_subnet_id_subnets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], name=op.f('fk_firewall_rules_source_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_subnet_id'], ['subnets.id'], name=op.f('fk_firewall_rules_source_subnet_id_subnets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firewall_rules'))
    )
    with op.batch_alter_table('firewall_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firewall_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_firewall_rules_name'), ['name'], unique=False)

    op.create_table('hardware_components',
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('specs', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_hardware_components_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hardware_components'))
    )
    with op.batch_alter_table('hardware_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hardware_components_id'), ['id'], unique=False)

    op.create_table('logical_services',
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('purchase_type', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('custom_attributes', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_logical_services_device_id_devices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logical_services'))
    )
    with op.batch_alter_table('logical_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logical_services_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logical_services_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_logical_services_service_type'), ['service_type'], unique=False)

    op.create_table('maintenance_windows',
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('ticket_number', sa.String(), nullable=True),
    sa.Column('coordinator', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_maintenance_windows_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_windows'))
    )
    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_windows_id'), ['id'], unique=False)

    op.create_table('monitoring_items',
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('spec', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('external_link', sa.String(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('notification_method', sa.String(), nullable=True),
    sa.Column('logic', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_monitoring_items_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitoring_items'))
    )
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_items_status'), ['status'], unique=False)

    op.create_table('network_interfaces',
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('link_speed_gbps', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_network_interfaces_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_interfaces'))
    )
    with op.batch_alter_table('network_interfaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_interfaces_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_interfaces_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_interfaces_mac_address'), ['mac_address'], unique=True)

    op.create_table('port_connections',
    sa.Column('source_device_id', sa.Integer(), nullable=True),
    sa.Column('source_port', sa.String(), nullable=True),
    sa.Column('target_device_id', sa.Integer(), nullable=True),
    sa.Column('target_port', sa.String(), nullable=True),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('speed_gbps', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('cable_type', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], name=op.f('fk_port_connections_source_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], name=op.f('fk_port_connections_target_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_port_connections'))
    )
    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_connections_id'), ['id'], unique=False)

    op.create_table('rooms',
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('floor_level', sa.String(), nullable=True),
    sa.Column('hvac_zone', sa.String(), nullable=True),
    sa.Column('fire_suppression_type', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_rooms_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_id'), ['id'], unique=False)

    op.create_table('secret_vault',
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('secret_type', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('encrypted_payload', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_secret_vault_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret_vault'))
    )
    with op.batch_alter_table('secret_vault', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_vault_id'), ['id'], unique=False)

    op.create_table('racks',
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('total_u_height', sa.Integer(), nullable=True),
    sa.Column('max_power_kw', sa.Float(), nullable=True),
    sa.Column('typical_power_kw', sa.Float(), nullable=True),
    sa.Column('max_weight_kg', sa.Float(), nullable=True),
    sa.Column('cooling_type', sa.String(), nullable=True),
    sa.Column('pdu_a_id', sa.String(), nullable=True),
    sa.Column('pdu_b_id', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('last_site_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_racks_room_id_rooms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_racks'))
    )
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_racks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_racks_name'), ['name'], unique=False)

    op.create_table('service_secrets',
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['logical_services.id'], name=op.f('fk_service_secrets_service_id_logical_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_secrets'))
    )
    with op.batch_alter_table('service_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_secrets_id'), ['id'], unique=False)

    op.create_table('device_locations',
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('start_unit', sa.Integer(), nullable=True),
    sa.Column('size_u', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.String(), nullable=True),
    sa.Column('depth', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_locations_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], name=op.f('fk_device_locations_rack_id_racks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_locations'))
    )
    with op.batch_alter_table('device_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_locations_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_locations_id'))

    op.drop_table('device_locations')
    with op.batch_alter_table('service_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_secrets_id'))

    op.drop_table('service_secrets')
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_racks_name'))
        batch_op.drop_index(batch_op.f('ix_racks_id'))

    op.drop_table('racks')
    with op.batch_alter_table('secret_vault', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_vault_id'))

    op.drop_table('secret_vault')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_port_connections_id'))

    op.drop_table('port_connections')
    with op.batch_alter_table('network_interfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_interfaces_mac_address'))
        batch_op.drop_index(batch_op.f('ix_network_interfaces_ip_address'))
        batch_op.drop_index(batch_op.f('ix_network_interfaces_id'))

    op.drop_table('network_interfaces')
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_items_status'))
        batch_op.drop_index(batch_op.f('ix_monitoring_items_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_items_category'))

    op.drop_table('monitoring_items')
    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_windows_id'))

    op.drop_table('maintenance_windows')
    with op.batch_alter_table('logical_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logical_services_service_type'))
        batch_op.drop_index(batch_op.f('ix_logical_services_name'))
        batch_op.drop_index(batch_op.f('ix_logical_services_id'))

    op.drop_table('logical_services')
    with op.batch_alter_table('hardware_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hardware_components_id'))

    op.drop_table('hardware_components')
    with op.batch_alter_table('firewall_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firewall_rules_name'))
        batch_op.drop_index(batch_op.f('ix_firewall_rules_id'))

    op.drop_table('firewall_rules')
    with op.batch_alter_table('device_software', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_software_id'))

    op.drop_table('device_software')
    with op.batch_alter_table('device_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_relationships_id'))

    op.drop_table('device_relationships')
    with op.batch_alter_table('subnets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subnets_network_cidr'))
        batch_op.drop_index(batch_op.f('ix_subnets_id'))

    op.drop_table('subnets')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_name'))
        batch_op.drop_index(batch_op.f('ix_sites_id'))

    op.drop_table('sites')
    with op.batch_alter_table('settings_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_options_id'))
        batch_op.drop_index(batch_op.f('ix_settings_options_category'))

    op.drop_table('settings_options')
    with op.batch_alter_table('incident_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_logs_title'))
        batch_op.drop_index(batch_op.f('ix_incident_logs_id'))

    op.drop_table('incident_logs')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_system'))
        batch_op.drop_index(batch_op.f('ix_devices_serial_number'))
        batch_op.drop_index(batch_op.f('ix_devices_name'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))
        batch_op.drop_index(batch_op.f('ix_devices_asset_tag'))

    op.drop_table('devices')
    with op.batch_alter_table('data_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_flows_name'))
        batch_op.drop_index(batch_op.f('ix_data_flows_id'))

    op.drop_table('data_flows')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
