"""Sync schema

Revision ID: 88600fe61fa9
Revises: 
Create Date: 2026-03-27 13:50:43.952129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88600fe61fa9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logical_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('license_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('purchase_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('purchase_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vendor', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logical_services', schema=None) as batch_op:
        batch_op.drop_column('vendor')
        batch_op.drop_column('cost')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('purchase_type')
        batch_op.drop_column('license_key')
        batch_op.drop_column('license_type')

    # ### end Alembic commands ###
