"""add_rca_module

Revision ID: 8b355eb20621
Revises: 3860f2d3a61b
Create Date: 2026-04-02 15:15:49.131304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b355eb20621'
down_revision: Union[str, Sequence[str], None] = '3860f2d3a61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('team_members', sa.JSON(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('tasks_json', sa.JSON(), nullable=True),
    sa.Column('linked_device_ids', sa.JSON(), nullable=True),
    sa.Column('linked_service_ids', sa.JSON(), nullable=True),
    sa.Column('milestones_json', sa.JSON(), nullable=True),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('kpis_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)

    op.create_table('rca_records',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('trigger_source', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('severity_logic', sa.JSON(), nullable=True),
    sa.Column('initial_symptoms', sa.Text(), nullable=True),
    sa.Column('target_system', sa.String(), nullable=True),
    sa.Column('impacted_asset_ids', sa.JSON(), nullable=True),
    sa.Column('narrative_summary', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('cause_of_failure', sa.Text(), nullable=True),
    sa.Column('signature_indicator', sa.Text(), nullable=True),
    sa.Column('knowledge_id', sa.Integer(), nullable=True),
    sa.Column('monitoring_item_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_entries.id'], name=op.f('fk_rca_records_knowledge_id_knowledge_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monitoring_item_id'], ['monitoring_items.id'], name=op.f('fk_rca_records_monitoring_item_id_monitoring_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rca_records'))
    )
    with op.batch_alter_table('rca_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rca_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rca_records_title'), ['title'], unique=False)

    op.create_table('rca_mitigations',
    sa.Column('rca_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rca_id'], ['rca_records.id'], name=op.f('fk_rca_mitigations_rca_id_rca_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rca_mitigations'))
    )
    with op.batch_alter_table('rca_mitigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rca_mitigations_id'), ['id'], unique=False)

    op.create_table('rca_timeline_events',
    sa.Column('rca_id', sa.Integer(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('involved_pocs', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rca_id'], ['rca_records.id'], name=op.f('fk_rca_timeline_events_rca_id_rca_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rca_timeline_events'))
    )
    with op.batch_alter_table('rca_timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rca_timeline_events_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rca_timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rca_timeline_events_id'))

    op.drop_table('rca_timeline_events')
    with op.batch_alter_table('rca_mitigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rca_mitigations_id'))

    op.drop_table('rca_mitigations')
    with op.batch_alter_table('rca_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rca_records_title'))
        batch_op.drop_index(batch_op.f('ix_rca_records_id'))

    op.drop_table('rca_records')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###
