"""remove redundant vendor contact fields

Revision ID: 8dbb85b0243e
Revises: 8f60472be553
Create Date: 2026-05-18 09:12:21.025182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbb85b0243e'
down_revision: Union[str, Sequence[str], None] = '8f60472be553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('primary_phone')
        batch_op.drop_column('primary_email')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_email', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('primary_phone', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
