"""sync_missing_columns

Revision ID: 988d728e925c
Revises: 066668880dda
Create Date: 2026-04-02 07:46:26.587534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988d728e925c'
down_revision: Union[str, Sequence[str], None] = '066668880dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logical_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('supplier', sa.String(), nullable=True))
        batch_op.drop_column('vendor')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logical_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('supplier')
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###
