"""Add FirewallRule table

Revision ID: a63bac01a52e
Revises: 88600fe61fa9
Create Date: 2026-03-31 08:20:04.018956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63bac01a52e'
down_revision: Union[str, Sequence[str], None] = '88600fe61fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firewall_rules',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_device_id', sa.Integer(), nullable=True),
    sa.Column('source_subnet_id', sa.Integer(), nullable=True),
    sa.Column('source_custom_ip', sa.String(), nullable=True),
    sa.Column('dest_type', sa.String(), nullable=True),
    sa.Column('dest_device_id', sa.Integer(), nullable=True),
    sa.Column('dest_subnet_id', sa.Integer(), nullable=True),
    sa.Column('dest_custom_ip', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('port_range', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dest_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dest_subnet_id'], ['subnets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_subnet_id'], ['subnets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firewall_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firewall_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_firewall_rules_name'), ['name'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'devices', ['device_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('network_interfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_interfaces_mac_address'))
        batch_op.create_index(batch_op.f('ix_network_interfaces_mac_address'), ['mac_address'], unique=True)

    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_type', sa.String(), nullable=True))
        batch_op.alter_column('purpose',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_site_name', sa.String(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'rooms', ['room_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sites', ['site_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_name'))
        batch_op.create_index(batch_op.f('ix_sites_name'), ['name'], unique=True)

    with op.batch_alter_table('subnets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subnets_network_cidr'))
        batch_op.create_index(batch_op.f('ix_subnets_network_cidr'), ['network_cidr'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subnets_network_cidr'))
        batch_op.create_index(batch_op.f('ix_subnets_network_cidr'), ['network_cidr'], unique=False)

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_name'))
        batch_op.create_index(batch_op.f('ix_sites_name'), ['name'], unique=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sites', ['site_id'], ['id'])

    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'rooms', ['room_id'], ['id'])
        batch_op.drop_column('last_site_name')

    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.alter_column('purpose',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('link_type')

    with op.batch_alter_table('network_interfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_interfaces_mac_address'))
        batch_op.create_index(batch_op.f('ix_network_interfaces_mac_address'), ['mac_address'], unique=False)

    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'devices', ['device_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('firewall_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firewall_rules_name'))
        batch_op.drop_index(batch_op.f('ix_firewall_rules_id'))

    op.drop_table('firewall_rules')
    # ### end Alembic commands ###
