"""add_user_pool_versioning

Revision ID: b258baee2a92
Revises: 4fb7471f58a3
Create Date: 2026-04-24 08:05:27.261322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b258baee2a92'
down_revision: Union[str, Sequence[str], None] = '4fb7471f58a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pool_versions',
    sa.Column('version_label', sa.String(), nullable=True),
    sa.Column('snapshot_data', sa.JSON(), nullable=True),
    sa.Column('diff_summary', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_pool_versions'))
    )
    with op.batch_alter_table('user_pool_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_pool_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pool_versions_version_label'), ['version_label'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pool_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_pool_versions_version_label'))
        batch_op.drop_index(batch_op.f('ix_user_pool_versions_id'))

    op.drop_table('user_pool_versions')
    # ### end Alembic commands ###
