"""add_primary_personnel_id_to_vendors

Revision ID: b29df7d2ec3c
Revises: fd2f8a526cfe
Create Date: 2026-04-30 08:25:07.233737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29df7d2ec3c'
down_revision: Union[str, Sequence[str], None] = 'fd2f8a526cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_personnel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_vendors_primary_personnel_id_vendor_personnel'), 'vendor_personnel', ['primary_personnel_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_vendors_primary_personnel_id_vendor_personnel'), type_='foreignkey')
        batch_op.drop_column('primary_personnel_id')

    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
