"""add tenant_id to devices

Revision ID: b33081b478f8
Revises: a9d4c7b2e1f0
Create Date: 2026-06-13 22:10:22.993353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33081b478f8'
down_revision: Union[str, Sequence[str], None] = 'a9d4c7b2e1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_settings_category'))
        batch_op.drop_index(batch_op.f('ix_global_settings_id'))
        batch_op.drop_index(batch_op.f('ix_global_settings_key'))

    op.drop_table('global_settings')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_devices_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('external_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_entities_active_identity'), sqlite_where=sa.text('is_deleted = 0'))

    with op.batch_alter_table('far_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_far_history_mode_version', ['far_mode_id', 'version'])

    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_items_active_identity'), sqlite_where=sa.text('is_deleted = 0'))

    with op.batch_alter_table('rca_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_rca_history_rca_version', ['rca_id', 'version'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rca_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rca_history_rca_version', type_='unique')

    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_items_active_identity'), ['device_id', 'title', 'category', 'platform'], unique=1, sqlite_where=sa.text('is_deleted = 0'))

    with op.batch_alter_table('far_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_far_history_mode_version', type_='unique')

    with op.batch_alter_table('external_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_entities_active_identity'), ['name', 'type', 'owner_organization'], unique=1, sqlite_where=sa.text('is_deleted = 0'))

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_tenant_id'))
        batch_op.drop_column('tenant_id')

    op.create_table('global_settings',
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_settings'))
    )
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_settings_key'), ['key'], unique=1)
        batch_op.create_index(batch_op.f('ix_global_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_settings_category'), ['category'], unique=False)

    # ### end Alembic commands ###
