"""add_mac_vlan_to_connections

Revision ID: b474b807d83a
Revises: 370e69388728
Create Date: 2026-03-31 10:07:43.605534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b474b807d83a'
down_revision: Union[str, Sequence[str], None] = '370e69388728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_mac', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_vlan', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_mac', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target_vlan', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.drop_column('target_vlan')
        batch_op.drop_column('target_mac')
        batch_op.drop_column('source_vlan')
        batch_op.drop_column('source_mac')

    # ### end Alembic commands ###
