"""revamp_vendors

Revision ID: b50f3c68f0a2
Revises: 988d728e925c
Create Date: 2026-04-02 08:49:02.467711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b50f3c68f0a2'
down_revision: Union[str, Sequence[str], None] = '988d728e925c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('effective_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('covered_assets', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('scope_of_work', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('schedule', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('document_link', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_vendor_contracts_contract_number'))
        batch_op.create_index(batch_op.f('ix_vendor_contracts_contract_id'), ['contract_id'], unique=False)
        batch_op.drop_column('total_value')
        batch_op.drop_column('currency')
        batch_op.drop_column('status')
        batch_op.drop_column('contract_number')
        batch_op.drop_column('sow_summary')
        batch_op.drop_column('sow_details_json')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('primary_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_vendors_organization'))
        batch_op.drop_column('account_info')
        batch_op.drop_column('access_details')
        batch_op.drop_column('pc_info')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('organization')
        batch_op.drop_column('on_call_info')
        batch_op.drop_column('work_schedule')

    op.create_table('vendor_personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('company_email', sa.String(), nullable=True),
    sa.Column('internal_email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('accounts', sa.JSON(), nullable=True),
    sa.Column('pcs', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_personnel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_personnel_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_personnel_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_schedule', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('on_call_info', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('organization', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pc_info', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('access_details', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('account_info', sqlite.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vendors_organization'), ['organization'], unique=False)
        batch_op.drop_column('country')
        batch_op.drop_column('primary_phone')
        batch_op.drop_column('primary_email')

    with op.batch_alter_table('vendor_personnel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_personnel_name'))
        batch_op.drop_index(batch_op.f('ix_vendor_personnel_id'))

    op.drop_table('vendor_personnel')

    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('sow_details_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('sow_summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('contract_number', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('total_value', sa.FLOAT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_vendor_contracts_contract_id'))
        batch_op.create_index(batch_op.f('ix_vendor_contracts_contract_number'), ['contract_number'], unique=False)
        batch_op.drop_column('document_link')
        batch_op.drop_column('schedule')
        batch_op.drop_column('scope_of_work')
        batch_op.drop_column('covered_assets')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('effective_date')
        batch_op.drop_column('contract_id')

    # ### end Alembic commands ###
