"""add farm and request link to port connections

Revision ID: bc27645123c4
Revises: 3e604a042903
Create Date: 2026-05-27 09:42:14.680609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc27645123c4'
down_revision: Union[str, Sequence[str], None] = '3e604a042903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('request_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.drop_column('request_link')
        batch_op.drop_column('farm')

    # ### end Alembic commands ###
