"""add_vendor_knowledge_investigation_tables

Revision ID: c4ebee015e2d
Revises: 256902a5e7d9
Create Date: 2026-04-01 08:27:26.564390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ebee015e2d'
down_revision: Union[str, Sequence[str], None] = '256902a5e7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('systems', sa.JSON(), nullable=True),
    sa.Column('impacted_device_ids', sa.JSON(), nullable=True),
    sa.Column('assigned_team', sa.String(), nullable=True),
    sa.Column('trigger_event', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('resolution_steps', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_title'), ['title'], unique=False)

    op.create_table('knowledge_entries',
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('question_context', sa.Text(), nullable=True),
    sa.Column('is_answered', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('impacted_systems', sa.JSON(), nullable=True),
    sa.Column('linked_device_ids', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_entries'))
    )
    with op.batch_alter_table('knowledge_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_entries_title'), ['title'], unique=False)

    op.create_table('vendors',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('pc_info', sa.JSON(), nullable=True),
    sa.Column('account_info', sa.JSON(), nullable=True),
    sa.Column('access_details', sa.Text(), nullable=True),
    sa.Column('work_schedule', sa.Text(), nullable=True),
    sa.Column('on_call_info', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_organization'), ['organization'], unique=False)

    op.create_table('investigation_progress',
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('entry_text', sa.Text(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=True),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_progress_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_progress'))
    )
    with op.batch_alter_table('investigation_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_progress_id'), ['id'], unique=False)

    op.create_table('vendor_contracts',
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sow_summary', sa.Text(), nullable=True),
    sa.Column('sow_details_json', sa.JSON(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_contracts_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_contracts'))
    )
    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_contracts_contract_number'), ['contract_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_contracts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_contracts_title'), ['title'], unique=False)

    op.create_table('contract_coverage',
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('support_tier', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['vendor_contracts.id'], name=op.f('fk_contract_coverage_contract_id_vendor_contracts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_contract_coverage_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_coverage'))
    )
    with op.batch_alter_table('contract_coverage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_coverage_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_coverage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_coverage_id'))

    op.drop_table('contract_coverage')
    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_contracts_title'))
        batch_op.drop_index(batch_op.f('ix_vendor_contracts_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_contracts_contract_number'))

    op.drop_table('vendor_contracts')
    with op.batch_alter_table('investigation_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_progress_id'))

    op.drop_table('investigation_progress')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_organization'))
        batch_op.drop_index(batch_op.f('ix_vendors_name'))
        batch_op.drop_index(batch_op.f('ix_vendors_id'))

    op.drop_table('vendors')
    with op.batch_alter_table('knowledge_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_entries_title'))
        batch_op.drop_index(batch_op.f('ix_knowledge_entries_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_entries_category'))

    op.drop_table('knowledge_entries')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_title'))
        batch_op.drop_index(batch_op.f('ix_investigations_id'))

    op.drop_table('investigations')
    # ### end Alembic commands ###
