"""add_service_fields

Revision ID: cd1dc3f9356b
Revises: b474b807d83a
Create Date: 2026-03-31 10:27:37.334058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1dc3f9356b'
down_revision: Union[str, Sequence[str], None] = 'b474b807d83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logical_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('documentation_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('installation_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logical_services', schema=None) as batch_op:
        batch_op.drop_column('installation_date')
        batch_op.drop_column('documentation_link')
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
