"""add_monitoring_versioning

Revision ID: d16649b5c596
Revises: 45d2a3a171dc
Create Date: 2026-04-10 10:12:54.793126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16649b5c596'
down_revision: Union[str, Sequence[str], None] = '45d2a3a171dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_history',
    sa.Column('monitoring_item_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['monitoring_item_id'], ['monitoring_items.id'], name=op.f('fk_monitoring_history_monitoring_item_id_monitoring_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitoring_history'))
    )
    with op.batch_alter_table('monitoring_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_history_id'), ['id'], unique=False)

    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
    
    op.execute("UPDATE monitoring_items SET version = 1 WHERE version IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('monitoring_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_history_id'))

    op.drop_table('monitoring_history')
    # ### end Alembic commands ###
