"""add status to port_connections

Revision ID: d1e55c4db1ab
Revises: 640471344358
Create Date: 2026-04-24 13:14:03.209942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e55c4db1ab'
down_revision: Union[str, Sequence[str], None] = '640471344358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_connections', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
