"""add_impact_to_monitoring_items

Revision ID: dc85bd757294
Revises: 26f7a74f2a4d
Create Date: 2026-04-09 11:20:11.049170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc85bd757294'
down_revision: Union[str, Sequence[str], None] = '26f7a74f2a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.drop_column('impact')

    # ### end Alembic commands ###
