"""add_is_deleted_and_owner_id_to_monitoring

Revision ID: e72b9b8626d3
Revises: dc85bd757294
Create Date: 2026-04-09 14:52:15.023444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72b9b8626d3'
down_revision: Union[str, Sequence[str], None] = 'dc85bd757294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_items', schema=None) as batch_op:
        batch_op.drop_column('owner_id')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
