"""add_knowledge_qa_and_update_entries

Revision ID: e8a537d7e66c
Revises: b29df7d2ec3c
Create Date: 2026-04-30 09:29:09.429275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a537d7e66c'
down_revision: Union[str, Sequence[str], None] = 'b29df7d2ec3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_qa',
    sa.Column('knowledge_id', sa.Integer(), nullable=True),
    sa.Column('parent_qa_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_team', sa.String(), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=True),
    sa.Column('is_answer', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_entries.id'], name=op.f('fk_knowledge_qa_knowledge_id_knowledge_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_qa_id'], ['knowledge_qa.id'], name=op.f('fk_knowledge_qa_parent_qa_id_knowledge_qa'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_qa'))
    )
    with op.batch_alter_table('knowledge_qa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_qa_id'), ['id'], unique=False)

    with op.batch_alter_table('knowledge_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_entries', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('knowledge_qa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_qa_id'))

    op.drop_table('knowledge_qa')
    # ### end Alembic commands ###
