"""add_infrastructure_plans

Revision ID: f3b4e2f663c9
Revises: bc27645123c4
Create Date: 2026-05-29 07:06:35.497721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b4e2f663c9'
down_revision: Union[str, Sequence[str], None] = 'bc27645123c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure_plans',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('racks_config', sa.JSON(), nullable=True),
    sa.Column('virtual_racks_data', sa.JSON(), nullable=True),
    sa.Column('plan_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_infrastructure_plans'))
    )
    with op.batch_alter_table('infrastructure_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infrastructure_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_infrastructure_plans_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('infrastructure_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infrastructure_plans_name'))
        batch_op.drop_index(batch_op.f('ix_infrastructure_plans_id'))

    op.drop_table('infrastructure_plans')
    # ### end Alembic commands ###
