"""sync_vendor_contracts_schema

Revision ID: fd2f8a526cfe
Revises: 485b2b4beada
Create Date: 2026-04-29 08:34:42.331068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2f8a526cfe'
down_revision: Union[str, Sequence[str], None] = '485b2b4beada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('covered_systems', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('previous_contract_changes', sa.Text(), nullable=True))

    with op.batch_alter_table('vendor_personnel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_original', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_personnel', schema=None) as batch_op:
        batch_op.drop_column('name_original')

    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.drop_column('previous_contract_changes')
        batch_op.drop_column('covered_systems')

    # ### end Alembic commands ###
