export const OPERATIONAL_WORKSPACE_MATRIX = [
  {
    key: 'monitoring',
    route: '/monitoring',
    source: 'frontend/src/components/MonitoringGrid.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: 'h1:has-text("Monitoring")',
    spec: 'frontend/tests/monitoring-workflows.spec.ts',
  },
  {
    key: 'external',
    route: '/external',
    source: 'frontend/src/components/External.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: 'h1:has-text("External")',
    spec: 'frontend/tests/external-workflows.spec.ts',
  },
  {
    key: 'services',
    route: '/services',
    source: 'frontend/src/components/ServicesReal.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: 'h1:has-text("Services")',
    spec: 'frontend/tests/service-workflows.spec.ts',
  },
  {
    key: 'network',
    route: '/network',
    source: 'frontend/src/components/NetworkReal.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: 'h1:has-text("Network")',
    spec: 'frontend/tests/network-workflows.spec.ts',
  },
  {
    key: 'far',
    route: '/far',
    source: 'frontend/src/components/FAR.tsx',
    shell: 'OperationalWorkspaceShell (custom body)',
    selector: 'h1:has-text("Failure Matrix")',
    spec: 'frontend/tests/far-workflows.spec.ts',
  },
  {
    key: 'research',
    route: '/research',
    source: 'frontend/src/components/Research.tsx',
    shell: 'OperationalWorkspaceShell (custom body)',
    selector: 'h1:has-text("Research")',
    spec: 'frontend/tests/research-workflows.spec.ts',
  },
  {
    key: 'assets',
    route: '/asset',
    source: 'frontend/src/components/Assets.tsx',
    shell: 'AssetGoldenShellScaffold',
    selector: 'h1:has-text("Assets")',
    spec: 'frontend/tests/assets-workflows.spec.ts',
  },
  {
    key: 'vendors',
    route: '/vendors',
    source: 'frontend/src/components/Vendor.tsx',
    shell: 'OperationalWorkspaceFrame',
    selector: 'h1:has-text("Vendors")',
    spec: 'frontend/tests/vendor-workflows.spec.ts',
  },
  {
    key: 'settings-standards',
    route: '/settings?tab=standards',
    source: 'frontend/src/components/SettingsStandards.tsx',
    shell: 'PageHeader / PageToolbar',
    selector: 'h1:has-text("Settings")',
    spec: 'frontend/tests/settings-standards.spec.ts',
  },
] as const;
