export const OPERATIONAL_WORKSPACE_MATRIX = [
  {
    key: 'monitoring',
    route: '/monitoring',
    source: 'frontend/src/components/MonitoringGrid.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: 'text=Monitoring',
    spec: 'frontend/tests/monitoring-workflows.spec.ts',
  },
  {
    key: 'external',
    route: '/external',
    source: 'frontend/src/components/External.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: 'text=External Intelligence',
    spec: 'frontend/tests/external-workflows.spec.ts',
  },
  {
    key: 'services',
    route: '/services',
    source: 'frontend/src/components/ServicesReal.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: 'text=Service Registry',
    spec: 'frontend/tests/service-workflows.spec.ts',
  },
  {
    key: 'network',
    route: '/network',
    source: 'frontend/src/components/NetworkReal.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: 'text=Network',
    spec: 'frontend/tests/network-workflows.spec.ts',
  },
  {
    key: 'far',
    route: '/far',
    source: 'frontend/src/components/FAR.tsx',
    shell: 'OperationalWorkspaceShell (custom body)',
    selector: 'text=Failure Inventory Maturity Profile',
    spec: 'frontend/tests/far-workflows.spec.ts',
  },
  {
    key: 'research',
    route: '/research',
    source: 'frontend/src/components/Research.tsx',
    shell: 'OperationalWorkspaceShell (custom body)',
    selector: 'text=Research Matrix',
    spec: 'frontend/tests/research-workflows.spec.ts',
  },
  {
    key: 'assets',
    route: '/asset',
    source: 'frontend/src/components/assets/AssetGoldenOperationalWorkspace.tsx',
    shell: 'AssetGoldenShellScaffold',
    selector: 'text=Registry Scope',
    spec: 'frontend/tests/assets-workflows.spec.ts',
  },
  {
    key: 'vendors',
    route: '/vendors',
    source: 'frontend/src/components/VendorsReal.tsx',
    shell: 'OperationalWorkspaceFrame',
    selector: 'text=Vendors',
    spec: 'frontend/tests/vendor-workflows.spec.ts',
  },
  {
    key: 'settings-standards',
    route: '/settings?tab=standards',
    source: 'frontend/src/components/SettingsStandards.tsx',
    shell: 'PageHeader / PageToolbar',
    selector: 'text=Operational Standards Reference',
    spec: 'frontend/tests/settings-standards.spec.ts',
  },
] as const;
