export const OPERATIONAL_WORKSPACE_MATRIX = [
  {
    key: 'monitoring',
    route: '/monitoring',
    source: 'frontend/src/components/monitoring/MonitoringGrid.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: '[data-testid="monitoring-grid"]',
    spec: 'frontend/tests/monitoring-workflows.spec.ts',
  },
  {
    key: 'external',
    route: '/external',
    source: 'frontend/src/components/External.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: '[data-testid="external-view"]',
    spec: 'frontend/tests/external-workflows.spec.ts',
  },
  {
    key: 'services',
    route: '/services',
    source: 'frontend/src/components/Services.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: '[data-testid="services-view"]',
    spec: 'frontend/tests/service-workflows.spec.ts',
  },
  {
    key: 'network',
    route: '/network',
    source: 'frontend/src/components/NetworkReal.tsx',
    shell: 'OperationalWorkspaceShell',
    selector: '[data-testid="network-view"]',
    spec: 'frontend/tests/network-workflows.spec.ts',
  },
  {
    key: 'far',
    route: '/far',
    source: 'frontend/src/components/FAR.tsx',
    shell: 'OperationalWorkspaceShell (custom body)',
    selector: '[data-testid="far-view"]',
    spec: 'frontend/tests/far-workflows.spec.ts',
  },
  {
    key: 'research',
    route: '/research',
    source: 'frontend/src/components/Research.tsx',
    shell: 'OperationalWorkspaceShell (custom body)',
    selector: '[data-testid="research-view"]',
    spec: 'frontend/tests/research-workflows.spec.ts',
  },
  {
    key: 'assets',
    route: '/asset',
    source: 'frontend/src/components/Assets.tsx',
    shell: 'AssetGoldenShellScaffold',
    selector: '[data-testid="asset-grid"]',
    spec: 'frontend/tests/assets-workflows.spec.ts',
  },
  {
    key: 'vendors',
    route: '/vendors',
    source: 'frontend/src/components/Vendor.tsx',
    shell: 'OperationalWorkspaceFrame',
    selector: '[data-testid="vendor-view"]',
    spec: 'frontend/tests/vendor-workflows.spec.ts',
  },
  {
    key: 'settings-standards',
    route: '/settings?tab=standards',
    source: 'frontend/src/components/SettingsStandards.tsx',
    shell: 'PageHeader / PageToolbar',
    selector: '[data-testid="settings-standards"]',
    spec: 'frontend/tests/settings-standards.spec.ts',
  },
] as const;
